-- 1. Creation of the reconciled layer table
CREATE TABLE IF NOT EXISTS reconciled.movies (
    movie_id SERIAL PRIMARY KEY,
    imdb_id VARCHAR(20),
    tmdb_id INT,
    title VARCHAR(500),
    release_year INT,
    budget NUMERIC,
    revenue NUMERIC,
    runtime INT,
    imdb_rating NUMERIC(3,1),
    imdb_votes INT,
    tmdb_rating NUMERIC(3,1),
    tmdb_votes INT
);

-- 2. Cleaning and reconciliation of data from Kaggle and IMDb
TRUNCATE TABLE reconciled.movies;

INSERT INTO reconciled.movies (
    imdb_id, tmdb_id, title, release_year, budget, revenue, runtime, 
    imdb_rating, imdb_votes, tmdb_rating, tmdb_votes
)
SELECT 
    -- Keep IMDb canonical identifier
    i."tconst" AS imdb_id,
    CAST(l."tmdbId" AS INT) AS tmdb_id,
    
    -- Cleanup: take original title from Kaggle, fallback to IMDb if missing
    COALESCE(k."original_title", i."primaryTitle") AS title,
    
    -- Cleanup: handle missing years from IMDb
    CASE 
        WHEN i."startYear" ~ '^[0-9]{4}$' THEN CAST(i."startYear" AS INT)
        ELSE NULL 
    END AS release_year,
    
    -- Cast financial metrics (handling dirty values)
    CASE 
        WHEN CAST(k."budget" AS VARCHAR) ~ '^[0-9]+(\.[0-9]+)?$' AND CAST(k."budget" AS NUMERIC) > 0 
        THEN CAST(k."budget" AS NUMERIC)
        ELSE NULL 
    END AS budget,
    CASE 
        WHEN CAST(k."revenue" AS VARCHAR) ~ '^[0-9]+(\.[0-9]+)?$' AND CAST(k."revenue" AS NUMERIC) > 0 
        THEN CAST(k."revenue" AS NUMERIC)
        ELSE NULL 
    END AS revenue,
    
    -- Cleanup runtime
    CASE 
        WHEN i."runtimeMinutes" ~ '^[0-9]+$' THEN CAST(i."runtimeMinutes" AS INT)
        ELSE NULL 
    END AS runtime,
    
    -- IMDb metrics
    CAST(r."averageRating" AS NUMERIC(3,1)) AS imdb_rating,
    CAST(r."numVotes" AS INT) AS imdb_votes,
    
    -- TMDB metrics
    CAST(k."vote_average" AS NUMERIC(3,1)) AS tmdb_rating,
    CAST(k."vote_count" AS INT) AS tmdb_votes

FROM staging.kaggle_movies_metadata k
-- Join using double quotes to respect the exact case generated by Pandas
JOIN staging.kaggle_links l ON CAST(k."id" AS VARCHAR) = CAST(l."tmdbId" AS VARCHAR)
-- Exact join: format numeric imdbId (e.g. 114709) to IMDb format (e.g. 'tt0114709')
JOIN staging.imdb_title_basics i ON CONCAT('tt', LPAD(CAST(l."imdbId" AS VARCHAR), 7, '0')) = i."tconst"
LEFT JOIN staging.imdb_title_ratings r ON i."tconst" = r."tconst"

-- Deduplication and validation filters
WHERE k."status" = 'Released' 
  AND i."titleType" = 'movie';


-- 3. Creation of reconciled directors table
CREATE TABLE IF NOT EXISTS reconciled.movie_directors (
    imdb_id VARCHAR(20),
    director_id VARCHAR(20),
    director_name VARCHAR(255),
    birth_year INT,
    death_year INT,
    PRIMARY KEY (imdb_id, director_id)
);

TRUNCATE TABLE reconciled.movie_directors;

-- Extraction of directors: unnesting comma-separated directors in title.crew
INSERT INTO reconciled.movie_directors (imdb_id, director_id, director_name, birth_year, death_year)
SELECT DISTINCT
    m.imdb_id,
    d.director_id,
    n."primaryName" AS director_name,
    CASE WHEN n."birthYear" ~ '^[0-9]{4}$' THEN CAST(n."birthYear" AS INT) ELSE NULL END AS birth_year,
    CASE WHEN n."deathYear" ~ '^[0-9]{4}$' THEN CAST(n."deathYear" AS INT) ELSE NULL END AS death_year
FROM reconciled.movies m
JOIN staging.imdb_title_crew c ON m.imdb_id = c."tconst"
CROSS JOIN LATERAL unnest(string_to_array(NULLIF(c."directors", '\N'), ',')) AS d(director_id)
JOIN staging.imdb_name_basics n ON d.director_id = n."nconst"
WHERE d.director_id IS NOT NULL;


-- 4. Creation of reconciled genres table (handling multivalued nature)
CREATE TABLE IF NOT EXISTS reconciled.movie_genres (
    imdb_id VARCHAR(20),
    genre_name VARCHAR(100),
    PRIMARY KEY (imdb_id, genre_name)
);

TRUNCATE TABLE reconciled.movie_genres;

-- Extraction of genres from IMDb title.basics
INSERT INTO reconciled.movie_genres (imdb_id, genre_name)
SELECT DISTINCT
    m.imdb_id,
    TRIM(g.genre) AS genre_name
FROM reconciled.movies m
JOIN staging.imdb_title_basics b ON m.imdb_id = b."tconst"
CROSS JOIN LATERAL unnest(string_to_array(NULLIF(b."genres", '\N'), ',')) AS g(genre)
WHERE g.genre IS NOT NULL AND g.genre <> '';

-- 5. Creation of reconciled movie geography table
CREATE TABLE IF NOT EXISTS reconciled.movie_geography (
    imdb_id VARCHAR(20) PRIMARY KEY,
    country_code VARCHAR(10),
    country_name VARCHAR(100),
    continent VARCHAR(50)
);

TRUNCATE TABLE reconciled.movie_geography;

-- Extract primary country from Kaggle metadata and assign continent
INSERT INTO reconciled.movie_geography (imdb_id, country_code, country_name, continent)
WITH parsed_countries AS (
    SELECT 
        m.imdb_id,
        -- Extract ISO country code and name using regex on JSON-like string
        SUBSTRING(k."production_countries" FROM '''iso_3166_1'': ''([A-Z]{2})''') AS country_code,
        SUBSTRING(k."production_countries" FROM '''name'': ''([^'']+)''') AS country_name
    FROM reconciled.movies m
    JOIN staging.kaggle_movies_metadata k ON m.tmdb_id = CAST(NULLIF(k."id", '') AS INT)
    WHERE k."production_countries" IS NOT NULL AND k."production_countries" <> '[]'
)
SELECT DISTINCT ON (imdb_id)
    imdb_id,
    country_code,
    country_name,
    CASE 
        WHEN country_code IN ('US', 'CA', 'MX') THEN 'North America'
        WHEN country_code IN ('GB', 'FR', 'DE', 'IT', 'ES', 'NL', 'RU', 'SE', 'DK', 'PL', 'BE', 'IE', 'NO') THEN 'Europe'
        WHEN country_code IN ('JP', 'CN', 'KR', 'IN', 'HK', 'TW', 'TH', 'IR', 'IL') THEN 'Asia'
        WHEN country_code IN ('AU', 'NZ') THEN 'Oceania'
        WHEN country_code IN ('BR', 'AR', 'CL', 'CO', 'PE') THEN 'South America'
        WHEN country_code IN ('ZA', 'EG', 'NG', 'MA', 'KE') THEN 'Africa'
        ELSE 'Other'
    END AS continent
FROM parsed_countries
WHERE country_code IS NOT NULL;